FROM node:24-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Set proxy environment variables
# ENV HTTP_PROXY=http://101.35.246.159:7890  HTTPS_PROXY=http://101.35.246.159:7890   NO_PROXY=localhost,127.0.0.1,backend,postgres,redis
# RUN npm config set proxy $HTTP_PROXY  && npm config set https-proxy $HTTPS_PROXY

# Install dependencies
RUN npm config set registry https://registry.npmmirror.com && npm install

# Copy application code
COPY . .

# Expose port
EXPOSE 5175

# Start development server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
